### ISSUE TITLE
Rearrange PlatformIO project and clean up

### ISSUE THREAD

**Issue by FiveTeethless** [dhebbeker/task-tracker#16]
> Thank you for porting the project. I was able to compile it successfully. :tada: 
> 
> Some topics which we may consider: 
> 
> - I am not sure whether the README files are necessary to be put under version control?
> - I hope that in file `time-tracker-pio/.vscode/extensions.json` the entry for `unwantedRecommendations` does not make any trouble. As this extension may be necessary for code formatting (see #11).
> - I am not a fan of splitting source and header files into different directories. Especially as I tend to logically structure the code with directories.

_Originally posted by @dhebbeker in https://github.com/dhebbeker/task-tracker/pull/15#pullrequestreview-1388883068_
            

I'll remove the READMEs and also put all header files into the source directory.
I've checked that this still compiles with PIO.

**Comment by dhebbeker** [comment]
Resolved by #17.
